DELETE http://localhost:8000/api/persons/2
###
GET http://localhost:8000/api/persons
###
POST http://localhost:8000/api/persons
content-type: application/json

{
    "name": "a",
    "number": "654"
}